language: python

python:
  - "2.7"

sudo: false

env:
  - DEPLOY_ENV=DEV
  - DJANGO_SETTINGS_MODULE=ccdb.settings

install:
  # Project configuration requirements.
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install pysqlite

script:
  - coverage run --source='.' manage.py test

after_success:
  - coveralls
